[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/upload-product-image"
  to = "/.netlify/functions/upload-product-image"
  status = 200

[[redirects]]
  from = "/razorpay/create-order"
  to = "/.netlify/functions/razorpay-create-order"
  status = 200

[[redirects]]
  from = "/razorpay/verify"
  to = "/.netlify/functions/razorpay-verify"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
